### ISSUE TITLE
Create install script

### ISSUE THREAD

**Issue by rochapaulo** [rochapaulo/Frank#11]
create make file to install, resolve dependencies...

**Comment by rkyamasaki** [comment]
Hello, i have a question to make about this issue.
Which sources files does the makefile have to compile?
I found those python files in the project
 - callbacks.py
 - configLoader.py
 - widgetHandlers.py
 - wuohoy.py

Is there any order to compile those files?

Best Regards.

**Comment by rochapaulo** [comment]
They aren't compiled... just interpreted.
So when we call: make install on terminal, the make must resolve dependencies, checking which is already installed and not installed... When they find an dependency missing, they must install.

eg:
$ make install
--- Installing Frank, resolving dependencies.
...
* python 2.7 - installed
* python-dev, downloading...

[====================================> 100%]

installing python-dev,

...
* ..

**Comment by rkyamasaki** [comment]
Hi, haha, you are right
i forgot that python is an interpreted language, and you don´t need to compile the source.
Thanks for the answer, now i do realize what is needed to do.

**Comment by rochapaulo** [comment]
Rubens, take a look at branch 'installer'. $ git checkout installer
I wrote an installer based on this post: https://packaging.python.org/en/latest/distributing.html
